import { PublicReleasePublisher } from "../server/public-release-publication.js";
import { syncReleaseFromObjectStore } from "../server/sync-release.js";
import http from "node:http";
import { proxyAdmin } from "../server/admin-proxy.js";
import test from "node:test";
import assert from "node:assert/strict";
import { spawn } from "node:child_process";
import { rm } from "node:fs/promises";
import { randomBytes } from "node:crypto";
import path from "node:path";
import net from "node:net";
import { reviewedFixture } from "./reviewed-fixture.js";

test("API management HTTP authorization and managed region requests preserve anonymous catalog and legacy keys", async t => {
 const f = await reviewedFixture();
 const publisher = new PublicReleasePublisher(f.options), plan = await publisher.plan();
 const run = await publisher.submit({planId:plan.planId,expectedBaselineSha256:plan.baselineBundle.sha256,surveyIds:["m42"],productIds:["product-1"]});
 assert.equal((await publisher.execute(run.runId)).status,"published");
 const installed=path.join(f.base,"installed");await syncReleaseFromObjectStore(f.store,installed);
 const socket = net.createServer(); await new Promise<void>(r=>socket.listen(0,"127.0.0.1",r)); const port=(socket.address() as net.AddressInfo).port; await new Promise<void>(r=>socket.close(()=>r()));
 const child=spawn(process.execPath,[path.resolve("node_modules/tsx/dist/cli.mjs"),"server/server.ts"],{env:{...process.env,HOST:"127.0.0.1",PORT:String(port),ASSET_RELEASE_ROOT:path.join(installed,"current"),ASSETS_CONTENT_ROOT:f.contentRoot,ASSETS_EVIDENCE_ROOT:path.join(f.base,"evidence"),ASSETS_ADMIN_ENABLED:"true",ASSETS_ADMIN_TOKEN:"fixture",ASSETS_WORKSPACE_API_KEY:"legacy-workspace",ASSETS_API_MASTER_KEY:randomBytes(32).toString("base64"),ASSETS_LLM_API_KEY:"",ASSETS_WAREHOUSE_ES_URL:"",ASSETS_KUBE_API_URL:"http://127.0.0.1:9"},stdio:["ignore","pipe","pipe"]});
 let logs="";child.stderr.on("data",c=>logs+=c);child.stdout.on("data",c=>logs+=c);
 t.after(async()=>{if(child.exitCode===null)await new Promise<void>(r=>{child.once("exit",()=>r());child.kill();});await rm(f.base,{recursive:true,force:true});});
 const base=`http://127.0.0.1:${port}`;for(let i=0;i<100;i++){try{if((await fetch(base+"/healthz")).ok)break;}catch{}if(child.exitCode!==null)throw new Error(logs);await new Promise(r=>setTimeout(r,100));}
 const route="/api/v1/admin/api-management", auth={Authorization:"Bearer fixture","Content-Type":"application/json"};
 assert.equal((await fetch(base+route)).status,401);
 const created=await fetch(base+route+"/keys",{method:"POST",headers:auth,body:JSON.stringify({name:"fixture",scopes:["region:query"],perMinute:2})});assert.equal(created.status,201);assert.equal(created.headers.get("cache-control"),"no-store");const key=await created.json();
 const view=await (await fetch(base+route,{headers:auth})).json();assert.equal(JSON.stringify(view).includes(key.key),false);
 const query=(token:string)=>fetch(base+"/api/v1/access/region-query",{method:"POST",headers:{"X-Assets-API-Key":token,"Content-Type":"application/json"},body:"{}"});
 assert.equal((await query("asa_live_unknown")).status,401);
 assert.equal((await query(key.key)).status,400,"authorized key reaches region validation");
 assert.equal((await query(key.key)).status,400);assert.equal((await query(key.key)).status,429);
 assert.equal((await query("legacy-workspace")).status,400,"legacy access unchanged");
 assert.equal((await fetch(base+route,{headers:{Authorization:`Bearer ${key.key}`}})).status,401,"managed key cannot administer");
 assert.equal((await fetch(base+"/api/v1/assets")).status,200);
 assert.equal((await fetch(base+route+`/keys/${key.id}/revoke`,{method:"POST",headers:auth})).status,200);
 assert.equal((await query(key.key)).status,401);
 const after=await (await fetch(base+route,{headers:auth})).json();assert.equal(after.keys[0].requests,4);assert.equal(after.keys[0].errors,4);
 // Browser enters a Key once, then uses an HttpOnly session through the site proxy.
 const issued=await (await fetch(base+route+"/keys",{method:"POST",headers:auth,body:JSON.stringify({name:"globe",scopes:["region:query"],perMinute:10})})).json();
 const proxy=http.createServer((req,res)=>proxyAdmin(req,res,base,true));await new Promise<void>(r=>proxy.listen(0,"127.0.0.1",r));
 t.after(()=>new Promise<void>(r=>proxy.close(()=>r())));
 const publicBase=`http://127.0.0.1:${(proxy.address() as net.AddressInfo).port}`;
 const unlock=(origin:string)=>fetch(publicBase+"/api/v1/access/unlock",{method:"POST",headers:{Origin:origin,"X-Assets-API-Key":issued.key,"Content-Type":"application/json"},body:"{}"});
 assert.equal((await unlock("https://other.example")).status,403);
 const unlocked=await unlock(publicBase);assert.equal(unlocked.status,200);const cookie=unlocked.headers.get("set-cookie")!;
 assert.match(cookie,/assets_download=managed\./);assert.match(cookie,/HttpOnly/);assert.match(cookie,/SameSite=Strict/);assert.equal(cookie.includes(issued.key),false);
 const browserQuery=(path:string,origin=publicBase)=>fetch(publicBase+path,{method:"POST",headers:{Origin:origin,Cookie:cookie.split(";")[0]!,"Content-Type":"application/json"},body:"{}"});
 assert.equal((await browserQuery("/api/v1/access/region-query")).status,400,"session reaches region validator");
 const reverse=await browserQuery("/api/v1/coverage/reverse-lookup");assert.equal(reverse.status,400);assert.equal((await reverse.json()).error,"layerIds required","preserve reverse-lookup input contract");
 const validPlan=await fetch(publicBase+"/api/v1/coverage/reverse-lookup",{method:"POST",headers:{Origin:publicBase,Cookie:cookie.split(";")[0]!,"Content-Type":"application/json"},body:JSON.stringify({layerIds:[f.layerId],order:8,cells:[163327]})});
 assert.equal(validPlan.status,200);const data=await validPlan.json();assert.equal(data.sources[0].layerId,f.layerId);assert.ok(data.downloadPlan);assert.deepEqual(data.downloadPlan.files,[],"authorization never invents missing science file indices");
 assert.equal((await browserQuery("/api/v1/coverage/reverse-lookup","https://other.example")).status,403);
 await fetch(base+route+`/keys/${issued.id}/revoke`,{method:"POST",headers:auth});
 assert.equal((await browserQuery("/api/v1/access/region-query")).status,401,"revoke invalidates already unlocked sessions");
 assert.equal((await browserQuery("/api/v1/coverage/reverse-lookup")).status,401);
 const passwordUnlock=await fetch(base+"/api/v1/access/unlock",{method:"POST",headers:{Origin:base,"Content-Type":"application/json"},body:JSON.stringify({password:"123"})});assert.equal(passwordUnlock.status,200,"original password preserved");
 const limited=await (await fetch(base+route+"/keys",{method:"POST",headers:auth,body:JSON.stringify({name:"limited browser",scopes:["region:query"],perMinute:1})})).json();
 const limitedUnlock=await fetch(base+"/api/v1/access/unlock",{method:"POST",headers:{Origin:base,"X-Assets-API-Key":limited.key,"Content-Type":"application/json"},body:"{}"});assert.equal(limitedUnlock.status,200);
 const limitQuery=await fetch(base+"/api/v1/coverage/reverse-lookup",{method:"POST",headers:{Origin:base,Cookie:limitedUnlock.headers.get("set-cookie")!.split(";")[0]!,"Content-Type":"application/json"},body:"{}"});assert.equal(limitQuery.status,429,"browser session retains Key rate limit");
 const stats=await (await fetch(base+route,{headers:auth})).json();assert.ok(stats.events.some((e:{id:string;route:string;status:number})=>e.id===issued.id&&e.route==="/api/v1/coverage/reverse-lookup"&&e.status===200));
 assert.equal(logs.includes(issued.key),false);
 assert.equal(logs.includes(key.key),false);
});
