{{- if .Values.admin.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "astro-survey-atlas-assets.fullname" . }}-admin
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "astro-survey-atlas-assets.labels" . | nindent 4 }}
automountServiceAccountToken: true
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "astro-survey-atlas-assets.fullname" . }}-admin
  namespace: {{ .Values.admin.warehouseNamespace }}
  labels:
    {{- include "astro-survey-atlas-assets.labels" . | nindent 4 }}
rules:
  - apiGroups: ["atlas.zhejianglab.org"]
    resources: ["scanrequests"]
    verbs: ["get", "list", "watch", "create"]
  - apiGroups: [""]
    resources: ["configmaps", "secrets", "persistentvolumeclaims"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "astro-survey-atlas-assets.fullname" . }}-admin
  namespace: {{ .Values.admin.warehouseNamespace }}
  labels:
    {{- include "astro-survey-atlas-assets.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "astro-survey-atlas-assets.fullname" . }}-admin
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "astro-survey-atlas-assets.fullname" . }}-admin
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "astro-survey-atlas-assets.fullname" . }}-admin-persistent-volumes
  labels:
    {{- include "astro-survey-atlas-assets.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["persistentvolumes"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "astro-survey-atlas-assets.fullname" . }}-admin-persistent-volumes
  labels:
    {{- include "astro-survey-atlas-assets.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "astro-survey-atlas-assets.fullname" . }}-admin
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "astro-survey-atlas-assets.fullname" . }}-admin-persistent-volumes
{{- end }}
