apiVersion: v1
kind: Service
metadata:
  name: {{ include "astro-survey-atlas-assets.fullname" . }}
  labels:
    {{- include "astro-survey-atlas-assets.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: {{ include "astro-survey-atlas-assets.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}

